### ISSUE TITLE
Error while setting up

### ISSUE THREAD

**Issue by abhi18av** [ochrons/scalajs-spa-tutorial#67]
Hi @ochrons ,

This is an awesome tutorial!!

I tried to learn Scala and Play through this a couple months ago and the app was working fine but today when I download the master , `cd` into it and do `sbt run`, I get a huge error trace. Could you kindly help me find a solution?

It compiles fine on the backend but when I open the `localhost 9000` and scalars begins compilation - it breaks. The only change that's I've had since last time is the installation of `ammonite` shell. 

```scala


--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Updating {file:/Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/}sharedJS...
[info] Resolving org.scala-js#scalajs-test-interface_2.11;0.6.13[info] Resolving org.scala-lang.modules#scala-parser-combinators[info] Resolving org.eclipse.jetty#jetty-websocket;8.1.16.v20140[info] Resolving org.eclipse.jetty#jetty-util;8.1.16.v20140903 .[info] Resolving org.eclipse.jetty#jetty-http;8.1.16.v20140903 .[info] Resolving org.eclipse.jetty#jetty-server;8.1.16.v20140903[info] Resolving org.eclipse.jetty.orbit#javax.servlet;3.0.0.v20[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Updating {file:/Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/}client...
[info] Resolving com.github.japgolly.scalajs-react#core_sjs0.6_2[info] Resolving com.github.japgolly.scalajs-react#extra_sjs0.6_[info] Resolving com.github.japgolly.scalacss#ext-react_sjs0.6_2[info] Resolving com.github.japgolly.scalacss#core_sjs0.6_2.11;0[info] Resolving com.github.japgolly.univeq#univeq_sjs0.6_2.11;1[info] Resolving org.scala-js#scalajs-test-interface_2.11;0.6.13[info] Resolving org.scala-lang.modules#scala-parser-combinators[info] Resolving org.eclipse.jetty#jetty-websocket;8.1.16.v20140[info] Resolving org.eclipse.jetty#jetty-util;8.1.16.v20140903 .[info] Resolving org.eclipse.jetty#jetty-http;8.1.16.v20140903 .[info] Resolving org.eclipse.jetty#jetty-server;8.1.16.v20140903[info] Resolving org.eclipse.jetty.orbit#javax.servlet;3.0.0.v20[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/shared/.js/target/scala-2.11/classes...
[info] Compiling 18 Scala sources to /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/client/target/scala-2.11/classes...
[info] Fast optimizing /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/client/target/scala-2.11/client-fastopt.js
[info] Compiling 8 Scala sources and 1 Java source to /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/scala-2.11/classes...
[info] LESS compiling on 1 source(s)
[error] /usr/bin/less:1
[error] (function (exports, require, module, __filename, __dirname) { ����
[error]                                                               ^
[error] SyntaxError: Invalid or unexpected token
[error]     at createScript (vm.js:56:10)
[error]     at Object.runInThisContext (vm.js:97:10)
[error]     at Module._compile (module.js:542:28)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
[error]     at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16
[info]
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /usr/bin/less:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (server/web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /usr/bin/less:1
[error] (function (exports, require, module, __filename, __dirname) { ����
[error]                                                               ^
[error] SyntaxError: Invalid or unexpected token
[error]     at createScript (vm.js:56:10)
[error]     at Object.runInThisContext (vm.js:97:10)
[error]     at Module._compile (module.js:542:28)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
[error]     at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16
[info] LESS compiling on 1 source(s)
[error] /usr/bin/less:1
[error] (function (exports, require, module, __filename, __dirname) { ����
[error]                                                               ^
[error] SyntaxError: Invalid or unexpected token
[error]     at createScript (vm.js:56:10)
[error]     at Object.runInThisContext (vm.js:97:10)
[error]     at Module._compile (module.js:542:28)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
[error]     at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16
[info]
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /usr/bin/less:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (server/web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /usr/bin/less:1
[error] (function (exports, require, module, __filename, __dirname) { ����
[error]                                                               ^
[error] SyntaxError: Invalid or unexpected token
[error]     at createScript (vm.js:56:10)
[error]     at Object.runInThisContext (vm.js:97:10)
[error]     at Module._compile (module.js:542:28)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
[error]     at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16
[error] application -

! @74a9jl1fo - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[JsTaskFailure: /usr/bin/less:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16
]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
Caused by: com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /usr/bin/less:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:9:16

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)


```

**Comment by abhi18av** [comment]
Tried again, after deleting the `.sbt` and reinstall `scala` and `sbt` via `brew`, to no success. The compilation fails, once I open up the front end in the browser.

**Comment by ochrons** [comment]
Perhaps your local `less` installation is broken?

**Comment by abhi18av** [comment]
@ochrons , so I tried what you suggested.
```sh

❯ npm install -g less
/Users/eklavya/.nvm/versions/node/v6.10.2/bin/lessc -> /Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/bin/lessc
/Users/eklavya/.nvm/versions/node/v6.10.2/lib
└─┬ less@2.7.2
  ├─┬ errno@0.1.4
  │ └── prr@0.0.0
  ├── graceful-fs@4.1.11
  ├── image-size@0.5.4
  ├── mime@1.3.6
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ promise@7.1.1
  │ └── asap@2.0.5
  ├─┬ request@2.81.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.6.0
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.1
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.4
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@4.2.1
  │ │ ├─┬ ajv@4.11.8
  │ │ │ ├── co@4.6.0
  │ │ │ └─┬ json-stable-stringify@1.0.1
  │ │ │   └── jsonify@0.0.0
  │ │ └── har-schema@1.0.5
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.4.0
  │ │ │ ├── assert-plus@1.0.0
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.13.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.1
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.7
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jsbn@0.1.1
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.15
  │ │ └── mime-db@1.27.0
  │ ├── oauth-sign@0.8.2
  │ ├── performance-now@0.2.0
  │ ├── qs@6.4.0
  │ ├── safe-buffer@5.1.0
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.6.0
  │ └── uuid@3.0.1
  └── source-map@0.5.6


   17s
❯ npm link less
/Users/eklavya/node_modules/less -> /Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less


```



And then ran `sbt run` again, the error message changed to this,


```sh


[info] LESS compiling on 1 source(s)
[error] /Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/lib/less/parser/parser.js:117
[error]             imports.contents[fileInfo.filename] = str;
[error]                    ^
[error]
[error] TypeError: Cannot read property 'contents' of undefined
[error]     at Object.parse (/Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/lib/less/parser/parser.js:117:20)
[error]     at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:97:20
[error]     at tryToString (fs.js:456:3)
[error]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
[info]
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/lib/less/parser/parser.js:117
            imports.contents[fileInfo.filename] = str;
                   ^

TypeError: Cannot read property 'contents' of undefined
    at Object.parse (/Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/lib/less/parser/parser.js:117:20)
    at /Users/eklavya/Projects/Polyglot/ScalaFlow/scalajs-spa-tutorial-master/server/target/less/lessc.js:97:20
    at tryToString (fs.js:456:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (server/web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /Users/eklavya/.nvm/versions/node/v6.10.2/lib/node_modules/less/lib/less/parser/parser.js:117


```

**Comment by ochrons** [comment]
Perhaps your node version is too old? I don't really know much about Node.js, so better check elsewhere for a solution to the `less` issue :D

**Comment by abhi18av** [comment]
Oh, that's doesn't seem likely. I'm on the latest stable version of the
nodejs distribution.


`node v6.10.2`

IIs there a docker image available for this?  I think I might have a better
luck with that :)

**Comment by abhi18av** [comment]
Hi again @ochrons , saw your `scaladays` talk - even more motivated for `scalajs` now :)

So, I've been at it trying to get the app working on my `macOS Sierra` machine just as it does on `ubuntu 16.04` machine, but so far no success.

I've tried a ton of things, and in the end I guess using docker images would solve my problem. Thing is, I'm a complete beginner at a lot of things here, so could you kindly, please provide me a kind of roadmap I can use to dockerize this tutorial and then develop this on my `macOS` machine?

I'd really appreciate it :smile:

**Comment by abhi18av** [comment]
Log Entry :=

japgolly, says that it might not be related to the css at all.

**Comment by abhi18av** [comment]
Damn, after trying this out with the latest `play-2.6` release and planning to switch the project to `sass` the only minimal change that did the job was to just use `sbt-less` version `1.1.0` as opposed to the default in the project and the play documentation which is, `1.0.6`.


```scala
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")
```
I'll close the issue now.

@ochrons  However, I'll note that since the [sbt-less](https://github.com/sbt/sbt-less) essentially seems dead why not offcially switch to [sbt-sassify](https://github.com/irundaia/sbt-sassify) instead?
