### ISSUE TITLE
Cant even run sbt on cloned repo

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [ochrons/scalajs-spa-tutorial#79]
I really would like to learn from the repo, but how can I when the first instruction in the tutorial doesnt even work...

```
/home/kalin/.jdks/openjdk-15.0.1/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Didea.managed=true -Dfile.encoding=UTF-8 -jar /home/kalin/.local/share/JetBrains/IntelliJIdea2020.3/Scala/launcher/sbt-launch.jar
[info] Loading project definition from /home/kalin/dev/experiments/scalajs-spa-tutorial/project
[info] Updating {file:/home/kalin/dev/experiments/scalajs-spa-tutorial/project/}scalajs-spa-tutorial-build...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/home/kalin/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.15/ivy-0.13.15.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Resolving org.scala-js#sbt-scalajs;0.6.18 ...
[info] Resolving org.scala-js#scalajs-tools_2.10;0.6.18 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving org.scala-js#scalajs-ir_2.10;0.6.18 ...
[info] Resolving org.scala-js#closure-compiler-java-6;v20160517 ...
[info] Resolving org.scala-js#closure-compiler-externs-java-6;v20160517 ...
[info] Resolving args4j#args4j;2.0.26 ...
[info] Resolving com.google.guava#guava;19.0 ...
[info] Resolving com.google.protobuf#protobuf-java;2.5.0 ...
[info] Resolving com.google.code.gson#gson;2.2.4 ...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Resolving com.googlecode.json-simple#json-simple;1.1.1 ...
[info] Resolving org.scala-js#scalajs-js-envs_2.10;0.6.18 ...
[info] Resolving io.apigee#rhino;1.7R5pre4 ...
[info] Resolving org.webjars#envjs;1.2 ...
[info] Resolving org.scala-js#scalajs-sbt-test-adapter_2.10;0.6.18 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving com.typesafe.sbt#sbt-less;1.0.6 ...
[info] Resolving org.webjars#less-node;1.7.5 ...
[info] Resolving org.webjars#source-map;0.1.31-2 ...
[info] Resolving org.webjars#amdefine;0.1.0-1 ...
[info] Resolving org.webjars#mkdirp;0.3.5 ...
[info] Resolving org.webjars#clean-css;2.2.7 ...
[info] Resolving com.typesafe.sbt#sbt-js-engine;1.0.1 ...
[info] Resolving com.typesafe#jse_2.10;1.0.0 ...
[info] Resolving com.typesafe#jse_2.10;1.0.0 ...
[error] Server access Error: Connection refused url=http://repo.typesafe.com/typesafe/releases/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[warn] 	module not found: com.typesafe#jse_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/kalin/.ivy2/local/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/kalin/.sbt/preloaded/com.typesafe/jse_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/kalin/.sbt/preloaded/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/jse_2.10/1.0.0/jse_2.10-1.0.0.pom
[info] Resolving com.typesafe#npm_2.10;1.0.0 ...
[info] Resolving com.typesafe#npm_2.10;1.0.0 ...
[error] Server access Error: Connection refused url=http://repo.typesafe.com/typesafe/releases/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[warn] 	module not found: com.typesafe#npm_2.10;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/kalin/.ivy2/local/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/kalin/.sbt/preloaded/com.typesafe/npm_2.10/1.0.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/kalin/.sbt/preloaded/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/npm_2.10/1.0.0/npm_2.10-1.0.0.pom
[info] Resolving com.typesafe.sbt#sbt-web;1.0.2 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.2 ...
[info] Resolving com.typesafe#config;1.2.0 ...
[info] Resolving org.webjars#webjars-locator;0.14 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.3.3 ...
[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.3.0 ...
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.3.3 ...
[info] Resolving com.typesafe.sbt#sbt-native-packager;1.0.0 ...
[info] Resolving org.apache.commons#commons-compress;1.4.1 ...
[info] Resolving org.tukaani#xz;1.0 ...
[info] Resolving org.vafer#jdeb;1.3 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving org.apache.commons#commons-compress;1.7 ...
[info] Resolving org.tukaani#xz;1.4 ...
[info] Resolving org.apache.maven#maven-core;3.2.2 ...
[info] Resolving org.apache.maven#maven-model;3.2.2 ...
[info] Resolving org.codehaus.plexus#plexus-utils;3.0.17 ...
[info] Resolving org.apache.maven#maven-settings;3.2.2 ...
[info] Resolving org.apache.maven#maven-settings-builder;3.2.2 ...
[info] Resolving org.codehaus.plexus#plexus-interpolation;1.19 ...
[info] Resolving org.codehaus.plexus#plexus-component-annotations;1.5.5 ...
[info] Resolving org.sonatype.plexus#plexus-sec-dispatcher;1.3 ...
[info] Resolving org.sonatype.plexus#plexus-cipher;1.4 ...
[info] Resolving org.apache.maven#maven-repository-metadata;3.2.2 ...
[info] Resolving org.apache.maven#maven-artifact;3.2.2 ...
[info] Resolving org.apache.maven#maven-plugin-api;3.2.2 ...
[info] Resolving org.eclipse.sisu#org.eclipse.sisu.plexus;0.0.0.M5 ...
[info] Resolving javax.enterprise#cdi-api;1.0 ...
[info] Resolving javax.annotation#jsr250-api;1.0 ...
[info] Resolving javax.inject#javax.inject;1 ...
[info] Resolving org.sonatype.sisu#sisu-guice;3.1.0 ...
[info] Resolving aopalliance#aopalliance;1.0 ...
[info] Resolving org.eclipse.sisu#org.eclipse.sisu.inject;0.0.0.M5 ...
[info] Resolving org.apache.maven#maven-model-builder;3.2.2 ...
[info] Resolving org.apache.maven#maven-aether-provider;3.2.2 ...
[info] Resolving org.eclipse.aether#aether-api;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-spi;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-util;0.9.0.M2 ...
[info] Resolving org.eclipse.aether#aether-impl;0.9.0.M2 ...
[info] Resolving org.codehaus.plexus#plexus-classworlds;2.5.1 ...
[info] Resolving org.apache.ant#ant;1.9.3 ...
[info] Resolving org.apache.ant#ant-launcher;1.9.3 ...
[info] Resolving org.bouncycastle#bcpg-jdk15on;1.51 ...
[info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
[info] Resolving com.typesafe.play#sbt-plugin;2.5.15 ...
[info] Resolving com.typesafe.play#sbt-routes-compiler_2.10;2.5.15 ...
[info] Resolving com.typesafe.play#twirl-api_2.10;1.1.1 ...
[info] Resolving org.apache.commons#commons-lang3;3.4 ...
[info] Resolving com.typesafe.play#sbt-run-support_2.10;2.5.15 ...
[info] Resolving com.typesafe.play#build-link;2.5.15 ...
[info] Resolving com.typesafe.play#play-exceptions;2.5.15 ...
[info] Resolving com.typesafe.play#twirl-compiler_2.10;1.1.1 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving com.typesafe.play#twirl-parser_2.10;1.1.1 ...
[info] Resolving com.typesafe#config;1.3.1 ...
[info] Resolving net.contentobjects.jnotify#jnotify;0.94-play-1 ...
[info] Resolving com.typesafe.sbt#sbt-twirl;1.1.1 ...
[info] Resolving com.typesafe.sbt#sbt-native-packager;1.1.5 ...
[info] Resolving org.apache.ant#ant;1.9.6 ...
[info] Resolving org.apache.ant#ant-launcher;1.9.6 ...
[info] Resolving com.typesafe.sbt#sbt-web;1.3.0 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.9 ...
[info] Resolving org.webjars#webjars-locator;0.26 ...
[info] Resolving org.webjars#webjars-locator-core;0.26 ...
[info] Resolving org.slf4j#slf4j-api;1.7.7 ...
[info] Resolving org.apache.commons#commons-compress;1.9 ...
[info] Resolving com.typesafe.sbt#sbt-js-engine;1.1.3 ...
[info] Resolving com.typesafe#jse_2.10;1.1.2 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.11 ...
[info] Resolving com.typesafe.akka#akka-contrib_2.10;2.3.11 ...
[info] Resolving com.typesafe.akka#akka-remote_2.10;2.3.11 ...
[info] Resolving io.netty#netty;3.8.0.Final ...
[info] Resolving org.uncommons.maths#uncommons-maths;1.2.2a ...
[info] Resolving com.typesafe.akka#akka-cluster_2.10;2.3.11 ...
[info] Resolving com.typesafe.akka#akka-persistence-experimental_2.10;2.3.11 ...
[info] Resolving org.iq80.leveldb#leveldb;0.5 ...
[info] Resolving org.iq80.leveldb#leveldb-api;0.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-all;1.7 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni;1.7 ...
[info] Resolving org.fusesource.hawtjni#hawtjni-runtime;1.8 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-osx;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux64;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win64;1.5 ...
[info] Resolving io.apigee.trireme#trireme-core;0.8.5 ...
[info] Resolving io.apigee.trireme#trireme-node10src;0.8.5 ...
[info] Resolving io.spray#spray-json_2.10;1.3.2 ...
[info] Resolving org.slf4j#slf4j-simple;1.7.12 ...
[info] Resolving org.slf4j#slf4j-api;1.7.12 ...
[info] Resolving com.typesafe#npm_2.10;1.1.1 ...
[info] Resolving org.webjars#npm;2.11.2 ...
[info] Resolving com.vmunier#sbt-web-scalajs;1.0.5 ...
[info] Resolving com.typesafe.sbt#sbt-digest;1.1.0 ...
[info] Resolving com.typesafe.sbt#sbt-gzip;1.0.0 ...
[info] Resolving org.scala-sbt#sbt;0.13.15 ...
[info] Resolving org.scala-sbt#main;0.13.15 ...
[info] Resolving org.scala-sbt#actions;0.13.15 ...
[info] Resolving org.scala-sbt#classpath;0.13.15 ...
[info] Resolving org.scala-sbt#interface;0.13.15 ...
[info] Resolving org.scala-sbt#io;0.13.15 ...
[info] Resolving org.scala-sbt#control;0.13.15 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.15 ...
[info] Resolving org.scala-sbt#collections;0.13.15 ...
[info] Resolving jline#jline;2.14.3 ...
[info] Resolving org.scala-sbt#api;0.13.15 ...
[info] Resolving org.scala-sbt#classfile;0.13.15 ...
[info] Resolving org.scala-sbt#logging;0.13.15 ...
[info] Resolving org.scala-sbt#process;0.13.15 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.15 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.15 ...
[info] Resolving org.scala-sbt#relation;0.13.15 ...
[info] Resolving org.scala-sbt#compile;0.13.15 ...
[info] Resolving org.scala-sbt#persist;0.13.15 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.15 ...
[info] Resolving org.scala-sbt#ivy;0.13.15 ...
[info] Resolving org.scala-sbt#cross;0.13.15 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.15 ...
[info] Resolving org.scala-sbt#task-system;0.13.15 ...
[info] Resolving org.scala-sbt#tasks;0.13.15 ...
[info] Resolving org.scala-sbt#tracking;0.13.15 ...
[info] Resolving org.scala-sbt#cache;0.13.15 ...
[info] Resolving org.scala-sbt#testing;0.13.15 ...
[info] Resolving org.scala-sbt#test-agent;0.13.15 ...
[info] Resolving org.scala-sbt#main-settings;0.13.15 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.15 ...
[info] Resolving org.scala-sbt#command;0.13.15 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.15 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.15 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe#jse_2.10;1.0.0: not found
[warn] 	:: com.typesafe#npm_2.10;1.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
sbt.ResolveException: unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
at xsbt.boot.Using$.withResource(Using.scala:10)
at xsbt.boot.Using$.apply(Using.scala:9)
at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
at xsbt.boot.Locks$.apply0(Locks.scala:31)
at xsbt.boot.Locks$.apply(Locks.scala:28)
at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
at sbt.IvySbt.withIvy(Ivy.scala:128)
at sbt.IvySbt.withIvy(Ivy.scala:125)
at sbt.IvySbt$Module.withModule(Ivy.scala:156)
at sbt.IvyActions$.updateEither(IvyActions.scala:168)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
at sbt.std.Transform$$anon$4.work(System.scala:63)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.Execute.work(Execute.scala:237)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
Invalid response.

```

**Comment by KevArellano** [comment]
What's your sbt version?
